### PR TITLE
Fix/ustar comments tags

### PR DESCRIPTION
**Pull request by conge**
Hi Austin,

I check the code since your last fix: it did not add the new comments or tags , it did not save personal ratings either, in csv.js or notion.js

so I forked your repo and tried my best to fix them.

Please review the changes.

Thanks.

Yang

### CODE REVIEW

**Comment by lizheming** [comment]
`star` field is what you want, and I have added `comment` and `tags` field also. So I can't understand what the pr want. btw, it seems abnormal that you get all field value without `subject` prefix.

**Comment by conge** [comment]
:)

You don't have to merge the pull request if you don't want those new fields. I don't need csv or notion output any more. JSON format worked very well forme.

But the current implementation don't add tags or comments or personal star.

Let me explain:

1. The `star` field in your implementation pointed to `subject.rating.star_count`, that's not a personal/user star but an average star by all readers. so I created `ustar` to hold the user star rating, and it gets data from `rating.star_count` which is what I wanted.
2. about the `comment` and `tags` fields, your implementation is trying to get the corresponding data from `subject.comment` and `subject.tags`. But in the json file from Douban API, neither `comment` or `tags` is under `subject`. that's why I was removing `subject.` from the code.

Hope these help.

Conge



JSON files work for me very well already.

**Comment by lizheming** [comment]
"an average star by all readers", that is `rating` field, `star` field is user star count. `comment` and `tags` field I'll check later.

**Comment by lizheming** [comment]
@conge Yes you're right, all of user data are at the root not `subject` field. your pr has some error I have fixed it and merged it. Thank you for your pr.

**Pull request merged**
